# Site settings
title: Digitimmy
description: 티미의 디지털 마케팅
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://digitimmy.com" # the base hostname & protocol for your site, e.g. http://example.com

# Banner Section
hero: 112.jpg
hero-title: Timmy's Digital Marketing
hero-description: Timmy's Little Marketing Tips

# Author - Creator
author-name: Timmy Ahn
author-image: 10.jpg
about-author: 광고대행사 AE, 호기심이 많으며 말하는 것을 좋아함
author-email: minyucka@gmail.com
author-facebook: https://facebook.com/minyuck
author-instagram: https://www.instagram.com/


# Social Media Links (Links are located in hero and footer)
facebook: https://facebook.com/minyuck
instagram: https://www.instagram.com/minyuck
linkedin: https://www.linkedin.com


# Contact Form Settings
contact-subtitle: Pok pok listicle meggings, gluten-free deep v you probably haven't heard of them taxidermy iPhone gentrify seitan. Kogi cornhole enamel. # Title for the subscription form.

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: pretty
paginate: 9
paginate_path: "/page/:num"

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

plugins:
  - jekyll-paginate
  - jekyll-feed

include:
  - _pages

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
